name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: macos-26

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Set up JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Cache Kotlin/Native toolchains
        uses: actions/cache@v4.3.0
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Install Vulkan SDK
        uses: technoir-lab/install-vulkan-sdk@v1.2.3
        with:
          version: 1.4.328.1
          cache: true

      - name: Set environment variables
        run: |
          echo "C_INCLUDE_PATH=${{ env.VULKAN_SDK }}/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=${{ env.VULKAN_SDK }}/lib" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build --scan
